### ISSUE TITLE
Curio needs creating

### ISSUE THREAD

**Issue by ProfDoof** [fireflamemm/The-Adventures-of-JRP#13]
The curio class needs to be finished and then implemented in at least one spot.

**Comment by mtwilliams-code** [comment]
Any preference on where the Curios are put? Also, where do we have our most current/informative map?

**Comment by ProfDoof** [comment]
If you will just create curio I or Ian can put it in somewhere tonight or you can come hang out with us in the COBA.

**Comment by ProfDoof** [comment]
I have created Curio and now am in the process of Debugging

**Comment by ProfDoof** [comment]
It seems to be working and I don't have time to do extensive debugging. If someone has time they are more than welcome to try and break it but otherwise this issue is closed.
